# Generated by Django 5.0.1 on 2024-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
    ]
