# Generated by Django 5.0.1 on 2024-03-07 18:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='default.jpg', upload_to='publisher/images/')),
                ('address', models.TextField()),
            ],
        ),
    ]
