# Generated by Django 5.0.1 on 2024-02-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='is_publisher',
        ),
    ]
