# Generated by Django 5.0.1 on 2024-02-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_alter_publisher_is_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
