# Generated by Django 5.0.1 on 2024-03-07 18:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(null=True)),
                ('biography', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='author/author_photos/')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
