# Generated by Django 5.0.1 on 2024-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='author/author_photos/'),
        ),
    ]
